spring:
  datasource:
    url: jdbc:postgresql://ep-nameless-block-actfwlrh-pooler.sa-east-1.aws.neon.tech/neondb
    username: neondb_owner
    password: npg_J5TLDs3qgNBp
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # Default profile
  profiles:
    active: dev

server:
  port: 8080
